name: $bog_pay_app

permissions: write-all

on:
  workflow_dispatch:
  push:
  pull_request:
  schedule:
  - cron: "0 7 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Manually clone mol_icon with retry
      run: |
        mkdir -p mol/icon
        for i in {1..5}; do
          git clone --depth 1 --single-branch https://github.com/nin-jin/mol_icon.git mol/icon && break || {
            echo "Attempt $i failed, retrying..."
            rm -rf mol/icon
            sleep 5
          }
        done
    
    - name: Configure Git timeout
      run: |
        git config --global http.postBuffer 524288000
        git config --global http.lowSpeedLimit 0
        git config --global http.lowSpeedTime 999999
    
    - uses: hyoo-ru/mam_build@master2
      with:
        package: 'bog/pay'
        modules: 'app'
        
    - uses: hyoo-ru/gh-deploy@v4.4.1
      if: github.ref == 'refs/heads/master'
      with:
        folder: 'bog/pay/app/-'
