name: $bog_pay_app

permissions: write-all

on:
  push:
  pull_request:
  schedule:
  - cron: "0 7 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Try build (attempt 1)
      id: attempt1
      continue-on-error: true
      uses: hyoo-ru/mam_build@master2
      with:
        package: 'bog/pay'
        modules: 'app'
        
    - name: Try build (attempt 2)
      if: steps.attempt1.outcome == 'failure'
      id: attempt2
      continue-on-error: true
      uses: hyoo-ru/mam_build@master2
      with:
        package: 'bog/pay'
        modules: 'app'
        
    - name: Try build (attempt 3)
      if: steps.attempt2.outcome == 'failure'
      uses: hyoo-ru/mam_build@master2
      with:
        package: 'bog/pay'
        modules: 'app'
        
    - uses: hyoo-ru/mam_build@master2
      with:
        package: 'bog/pay'
        modules: 'app'
        
    - uses: hyoo-ru/gh-deploy@v4.4.1
      if: github.ref == 'refs/heads/master'
      with:
        folder: 'bog/pay/app/-'
